language: ruby
sudo: enabled
dist: trusty
before_install:
  - sudo apt-get update
  - sudo apt-get install automake bison flex g++ git libboost1.55-all-dev libevent-dev libssl-dev libtool make pkg-config -y
  - wget http://mirror.reverse.net/pub/apache/thrift/0.10.0/thrift-0.10.0.tar.gz -O /tmp/thrift.tar.gz
  - cd /tmp && tar xvf thrift.tar.gz && cd thrift-0.10.0 && cmake . -DBUILD_COMPILER=OFF -DBUILD_C_GLIB=OFF -DBUILD_PYTHON=OFF && make -j && sudo make install
  - gem install bundler --no-document

rvm:
  - 1.9.3
  - 2.1.8
  - 2.2.1
  - 2.3.0
  - 2.4.0
script:
  # Please add to Rakefile instead of this section.
  - bundle exec rake
  - bundle exec rubocop
