language: ruby
sudo: false
dist: bionic

cache:
  ccache: true
  directories:
    - $HOME/thrift

env:
  global:
    - CC="ccache gcc"
    - CXX="ccache g++"
    - THRIFT_SHA256SUM="2289d02de6e8db04cbbabb921aeb62bfe3098c4c83f36eec6c31194301efa10b  thrift-0.10.0.tar.gz"
    - THRIFT_URL="http://mirror.reverse.net/pub/apache/thrift/0.10.0/thrift-0.10.0.tar.gz"
    - THRIFT_FILE="thrift-0.10.0.tar.gz"
    - THRIFT_DIR="thrift-0.10.0"

before_install:
  # don't do this in prod
  - bash ./travis-build-thrift.sh
  - export LIBRARY_PATH="$HOME/thrift/$THRIFT_DIR/lib:$LIBRARY_PATH"
  - export LD_LIBRARY_PATH="$HOME/thrift/$THRIFT_DIR/lib:$LD_LIBRARY_PATH"
  - export CPATH="$HOME/thrift/$THRIFT_DIR/lib/cpp/src:$HOME/thrift/$THRIFT_DIR:$CPATH"

rvm:
  - 1.9.3
  - 2.1.8
  - 2.2.1
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0

script:
  # Please add to Rakefile instead of this section.
  - bundle exec rake
  - bundle exec rubocop

addons:
  apt:
    packages:
      - automake
      - bison
      - build-essential
      - flex
      - g++
      - git
      - libboost-all-dev
      - libevent-dev
      - libssl-dev
      - libtool
      - make
      - pkg-config
